---
title: Adaptable art
hero_image: images/banner.png
description: Create a piece of adaptable artwork that displays on the SenseHAT to match its environment.
version: 4
listed: false
copyedit: false
last_tested: '2021-03-26'
steps:
- title: Introduction
- title: Design your animation
- title: Code your animation
- title: Sense the colour
- title: Time your animation
- title: Reflection
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
- title: Upgrade your project
- title: Share
- title: What next?
